// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjZZznE5n3HPL4EpHbjeRFC9P60huBYA',
    appId: '1:85234908547:web:a885e4c8c65ed6c34c0ab6',
    messagingSenderId: '85234908547',
    projectId: 'fitness-app-a2f39',
    authDomain: 'fitness-app-a2f39.firebaseapp.com',
    storageBucket: 'fitness-app-a2f39.appspot.com',
    measurementId: 'G-1CPVV755T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChmRUAnj0moYXqyyOX9dgJEnzaZwrwCx4',
    appId: '1:85234908547:android:02899d643dd7325a4c0ab6',
    messagingSenderId: '85234908547',
    projectId: 'fitness-app-a2f39',
    storageBucket: 'fitness-app-a2f39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_Whrva2TGlq9zD22cRa1WWszwa9pDqc',
    appId: '1:85234908547:ios:a5cb7d8f2ac117444c0ab6',
    messagingSenderId: '85234908547',
    projectId: 'fitness-app-a2f39',
    storageBucket: 'fitness-app-a2f39.appspot.com',
    iosClientId: '85234908547-btdvc4ifmj2q4m9n7525d3n2o7al9of8.apps.googleusercontent.com',
    iosBundleId: 'com.supitsparth.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_Whrva2TGlq9zD22cRa1WWszwa9pDqc',
    appId: '1:85234908547:ios:ce44b16abd7ad0df4c0ab6',
    messagingSenderId: '85234908547',
    projectId: 'fitness-app-a2f39',
    storageBucket: 'fitness-app-a2f39.appspot.com',
    iosClientId: '85234908547-lmqfs6egs9hp9rf9dl20bmr10kjjotii.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTracker',
  );
}
